// Generated by CoffeeScript 1.3.1
(function() {
  var Config, testConfig;

  require('./testHelper');

  Config = require('../config');

  testConfig = function(test) {
    test.equal(Config.port, 10000);
    test.equal(Config.timeout, 20);
    test.equal(Config.loggerType, "consoleLogger");
    return test.done();
  };

  module.exports.testConfig = testConfig;

}).call(this);
