// Generated by CoffeeScript 1.3.1
(function() {
  var Logger, testLogger;

  require('./testHelper');

  Logger = require('../src/logger');

  testLogger = function(test) {
    test.ok(true);
    return test.done();
  };

  module.exports.testLogger = testLogger;

}).call(this);
