// Generated by CoffeeScript 1.3.1
(function() {
  var Config;

  Config = {
    port: 10000,
    host: 'localhost',
    timeout: 20,
    loggerType: "consoleLogger"
  };

  module.exports = Config;

}).call(this);
