// Generated by CoffeeScript 1.3.1
(function() {
  var MockRequest, i, str, streams, _i;

  MockRequest = require('./socketConnect').MockRequest;

  streams = MockRequest.multipleConnections(1);

  str = "abc";

  for (i = _i = 0; _i <= 10000; i = ++_i) {
    str = str.concat("c");
  }

  console.log(str);

  streams[0].write(str);

}).call(this);
