// Generated by CoffeeScript 1.3.1
(function() {
  var Config, ConnectionManager, Pig, logger, net;

  net = require('net');

  Config = require('../config');

  logger = require('./logger');

  ConnectionManager = require('./connectionManager');

  Pig = (function() {

    Pig.name = 'Pig';

    function Pig() {
      this.cm = new ConnectionManager();
    }

    Pig.prototype.run = function() {
      var self, server;
      server = net.createServer(function(stream) {
        stream.setEncoding("utf8");
        stream.on('connect', function(socketFd) {
          logger.log('connect');
          return stream.write("hello\r\n");
        });
        stream.on('data', function(data) {
          logger.log('data');
          return stream.write(data);
        });
        return stream.on('end', function() {
          logger.log('end');
          return stream.end;
        });
      });
      self = this;
      server.on('connection', function(socket) {
        self.cm.add(socket);
        console.log(self.cm.cp);
        logger.log(self.cm.size());
        logger.log("connection");
        return console.log(socket);
      });
      server.listen(Config.port, Config.host);
      return logger.log("server running on port " + Config.port);
    };

    return Pig;

  })();

  module.exports = Pig;

}).call(this);
